require(
'plugins::Template',
function(T) {
	define(
	'app::whisper::template',
	T({
		"general" : '<table>{{#}}<tr class="items-list hijackdata {{#unreadCount}}items-list-hover{{/unreadCount}}" data-mid="{{{mid}}}"><td class="icon"><i class="inform-icon-msg-{{#recv_send}}sent{{^}}receive{{/recv_send}}"></i></td><td><div class="pic-know">{{#account}} <a href="{{{url}}}" target="_blank"><img src="{{ico}}" data-card="true" data-card-action="xpt={{{xpt}}}"></a> {{/account}}</div></td><td><div class="msg">{{#recv_send}}发给{{/recv_send}} {{#account}}<a href="{{{url}}}" target="_blank" data-card="true" data-card-action="xpt={{xpt}}">{{{title}}}</a>{{/account}}：</div><div class="content-box">{{#iscuted}}<a title="点击进入详细消息列表" href="#pp={{.account.xpt}}" action="whisper.detail" data-pp="{{.account.pp}}">{{/iscuted}} {{{filtered_content}}} {{#iscuted}}</a><a title="查看" href="#pp={{.account.xpt}}" action="whisper.detail" data-pp="{{.account.pp}}">查看&gt;&gt;</a>{{/iscuted}}</div><div class="date">{{#account}}<span class="del">{{#unreadCount}}<i class="ico-loudspeaker"></i>{{/unreadCount}}<a class="msg-num" href="#pp={{xpt}}" action="whisper.detail" data-pp="{{pp}}" title="点击进入详细消息列表">{{#unreadCount}}您收到了{{{}}}条新短消息{{^}}{{{count}}}条短消息{{/unreadCount}}</a><a href="javascript:;" action="whisper.send" data-nick="{{{title}}}">回复</a><a href="javascript:;" action="whisper.deleteAll" title="删除与{{{title}}}的所有消息" data-pp="{{{pp}}}"> <i class="inform-icon-del"></i></a></span>{{/account}} {{{time}}}</div></td></tr>{{/}}</table>',
		"detail" : '{{#}}<div class="releasebox {{#isrecv}}replay{{^}}mysay{{/isrecv}} hijackdata{{#tmp}} temp{{/tmp}}" data-mid="{{{mid}}}"><div class="items-list"><div class="avatar"><div class="pic-know">{{#from}} <a href="{{{url}}}" target="_blank" {{#xpt}}data-card="true" data-card-action="xpt={{{xpt}}}"{{/xpt}}><img src="{{{ico}}}"></a>{{/from}}</div></div><div class="content-box">{{#from}} <a href="{{{url}}}" target="_blank" {{#xpt}}data-card="true" data-card-action="xpt={{{xpt}}}"{{/xpt}}>{{{title}}}</a>{{^}}<a>我</a>{{/from}}:{{{filtered_content}}}</div><div class="date"><span class="del"><a href="javascript:;" action="whisper.delete"><i class="inform-icon-del"></i></a></span>{{{time}}}</div></div></div>{{/}}'
	}));
});
