require(
'plugins::Template',
function(T) {
	define(
	'app::widgets::template',
	T({
		"theme" : '<div id="skin_bar"><div class="themes-wrapper"><div class="theme-name-wrapper"><div class="theme-names groups">{{#}} <span class="group" title="{{{title}}}" action="show-group"><a href="javascript:;">{{{title}}}</a></span> {{/}}</div></div><div class="theme-page-wrapper"><a class="prev" href="javascript:;" title="上一页" action="prev"></a></div><div class="icons"></div><div class="theme-page-wrapper"><a class="next" href="javascript:;" title="下一页" action="next"></a></div></div><div class="theme-extends"><div class="theme-actions-wrapper"><div class="theme-actions"><span class="ui-btn btn-save" title="保存当前皮肤" action="save"><span>保存</span></span><span class="ui-btn btn-gray btn-cancel" title="取消设定" action="cancel"><span>取消</span></span></div><br class="clear" /></div></div></div>',
		"theme_list" : '<div class="list" style="width: {{{width}}}px">{{#themes}} <span style="background-image: url(http://s3.suc.itc.cn/themes/{{{id}}}/icon.jpg)"> <a class="skin" theme="{{{id}}}" href="javascript:;" action="wear-skin"><div class="title">{{{title}}}</div></a></span>{{/themes}}</div>',
		"group_sort" : '<div class="group-order-box"><div class="order-preview-wrapper"><h3>分组显示预览</h3><ul class="tabs-menu">{{{tabs}}}</ul></div><div class="group-list-wrapper"><h3>拖拽分组名称，调整分组顺序，点击文本还可编辑分组名称</h3><ul class="group-list">{{#groups}}<li data-gid="{{id}}"><a class="editable" title="点击进行编辑">{{name}}</a></li> {{/groups}}</ul></div></div>',
		"theme_custom" : '{{#weared}}<div class="bg_setting{{^url}} no-bg{{/url}}"><span class="bg-upload"{{#url}} style="background:{{{bg_sm}}} no-repeat center center"{{/url}}><a class="skin" href="javascript:;"><object id="theme_bg-upload"></object><div class="no-bg add-bg"><span class="no-uploading"><i></i><span class="text-up">添加背景图片</span></span><span class="progress"></span></div><div class="title have-bg">更换图片</div></a></span><span class="bg_option"><div class="hint upload-hint no-bg">点击左侧可以上传本地背景图片。<br/>支持jpg、jpeg、gif、png格式，请上传小于3M图片，过大的图片会影响你的展示效果哦~</div><span class="have-bg"><div class="row"><span class="hint cell">对齐方式</span><a id="i_select_Position" href="javascript:;" class="i-select cell">左对齐</a><span class="cell gray">选择背景图片对齐方式</span></div><div class="row"><span class="hint cell">显示方式</span><a id="i_select_Repeat" href="javascript:;" class="i-select cell">不平铺</a><span class="cell gray">选择背景图片显示方式</span></div><label action="reset-bg"><input type="checkbox"{{#custom}} checked="checked"{{/custom}} />使用自定义背景图片</label></span></span></div>{{/weared}}<div class="vr"></div><div class="right"><p class="hint color-hint">你还可以选择配色方案</p><div class="color-list">{{#colors}}<a href="javascript:;" action="custom-color" data-color="{{id}}" title="{{title}}" style="background-image: url(http://s3.suc.itc.cn/themes/{{id}}/icon.jpg)"></a>{{/colors}}</div></div>',
		"forward" : '<div class="forward-box clearfix emote-handler">{{+usericon}}<div class="forward-con"><div class="forward-fields"><textarea name="" id="" cols="50" rows="2"></textarea></div><div class="forward-options clearfix"><div class="forwoard-tip-txt">0 / {{chars}}</div><div class="pub-faces"><div style="width: 0; height: 0;"><div class="emotion-list" style="display: none;"></div></div><a href="javascript:;" action="emote"><span class="btn-emot"></span></a></div><ul>{{#origin}}<li><label> <input type="checkbox" checked="checked" /> 同时评论给{{unick}}</label></li> {{#fwd}}<li><label> <input type="checkbox" checked="checked" /> 同时评论给原文作者 {{unick}}</label></li> {{/fwd}}{{/origin}}</ul></div>{{#data}}<div class="forward-body clearfix"><h3>{{>username}} {{#album}} 的专辑 <a href="{{url}}" target="_blank">{{{title}}}</a></h3><p>{{{content}}}</p>{{/album}} {{#photo}} 的图片</h3><p>{{{content}}}</p>{{/photo}} {{#photos}} 的图片</h3> {{/photos}} {{#blog}} 的博客 <a href="{{url}}" target="_blank">{{title}}</a></h3><p>{{{content}}}</p>{{/blog}} {{#video}} 的视频 <a href="{{url}}" target="_blank">{{{title}}}</a></h3><p>{{{content}}}</p>{{/video}} {{#sentence}}<span class="user-suffix">：</span>{{{filtered_title}}}</h3>{{/sentence}} {{#qingsohu}}&nbsp;的新闻 <a href="{{url}}" target="_blank">{{{title}}}</a></h3><p>{{{content}}}</p>{{/qingsohu}}</div>{{/data}}</div></div>',
		"page" : '<div class="ui-pagination"><a class="null" href="javascript:;" data-page="1" action="page">首页</a> <a class="null" href="javascript:;" data-page="prev" action="page">上一页</a> <span class="page-num"><p style="display: none;"></p> <span class=""><span class="cpage">第<span>1</span>页</span><span class="btn-arrow"></span></span></span> <a class="txt" data-page="next" href="javascript:;" action="page">下一页</a> <a class="null" href="javascript:;" data-page="tail" action="page">末页</a></div>',
		"atTa" : '<div class="post-wrapper-inner emote-handler sentence-box" style="width: 388px"><div class="post-area" id="sentence_post_area"><div class="post-state-wrapper"><div style="display: none;" class="post-state success" id="post_state"></div></div><div class="textarea-wrapper post-state-success"><textarea rows="1" cols="60" id="onesentencetext" name="" style="height: 54px; display: inline; color: rgb(153, 153, 153);"></textarea></div></div><div class="post-action"><div class="post-options"><div><div class="emotion-list"></div></div><div class="pub-faces"><div class="clearfix"><a href="javascript:;" action="emote"><span class="btn-emot"></span></a></div></div></div><div class="post-btns"><div class="btn-submit"><a id="sentence_submit" href="javascript:void(0);"><span class="submit">发布</span></a></div><div class="txt-number"><span class="txt-number-now">0 / 300</span></div><div class="txt-error">请输入内容</div></div><div class="clear"></div></div></div>',
		"albumview" : '<div class="albumview"><!--[if IE 6]><div class="albumview-bg"></div><![endif]--><div class="albumview-wrapper origin"><a href="" target="_blank"></a></div><div class="albumview-wrapper pic"><a href="" target="_blank" title="查看原始图片"></a></div><div class="albumview-wrapper func"><a href="javascript:;" class="roleft clickHandler" action="roleft"><i></i><span class="tit">向左转图片</span></a> <a href="javascript:;" class="roright clickHandler" action="roright"><i></i><span class="tit">向右转图片</span></a> <a href="javascript:;" class="fwd clickHandler" action="forward"><span class="func-float"></span><i></i><span class="tit">转发此图片<span class="num"></span></span></a> <a href="javascript:;" class="cmt clickHandler" action="discuss"><span class="func-float"></span><i></i> <span class="tit">评论此图片<span class="num"></span></span></a></div><div class="albumview-wrapper desc"><div class="albumview-desc"><span></span></div></div><div class="albumview-body"><a href="javascript:;" class="albumview-close" title="关闭视图并返回到新鲜事列表"></a><div style="clear: both; height: 1px;"></div><div class="albumview-nav"><a href="javascript:;" title="下一张" class="albumview-next clickHandler" action="show" data-index="next"></a> <a href="javascript:;" title="上一张" class="albumview-prev clickHandler" action="show" data-index="prev"></a></div><div class="albumview-discuss"><textarea>说说你的看法</textarea><a href="javascript:;" class="discuss-post clickHandler" action="discuss.post"></a><span class="discuss-count"></span><span class="discuss-more"><label><input type="checkbox" />同时转发</label><a href="" target="_blank">查看评论(<span></span>条)</span></a></div><div class="albumview-count"><span></span></div></div><div class="albumview-bottombar"><div class="albumview-preview"></div></div></div>',
		"whisper" : [
			'<div class="whisper-wrapper">',
			'  {{^nick}}',
			'  <div style="width: 0; height: 0; overflow: visible">',
			'    <div class="nicks">',
			'      <div class="nicks-head"><i></i></div>',
			'      <ul></ul>',
			'    </div>',
			'  </div>',
			'  <label for="whisper_nick">收件人</label><input id="whisper_nick" type="text" /> <br class="clear" />',
			'  <div class="contact"></div>',
			'  {{/nick}}',
			'  <label for="whisper_content">内&nbsp;&nbsp;容</label>',
			'  <textarea id="whisper_content">{{content}}</textarea><span class="hint"><span>{{{chars}}}</span> / {{{chars}}} </span>',
			'  <a href="javascript:;" class="emote"><span class="btn-emot"></span>表情</a>',
			'</div>',
			'<br class="clear" />',
			'<div class="emotion-list"></div>',
			'<style type="text/css">.jquery-dialog.dialog-whisper .dialog-button-container { padding: 9px 0 7px; text-align: right; }</style>'
		].join('')
	}));
});
