require(
'plugins::Template',
function(T) {
	define(
	'app::assistant::template',
	T({
		"event" : '<div class="title"><a href="{{url}}" target="_blank">{{{btnTitle}}}</a></div><img class="icon" src="{{logo}}" /><div class="content">{{{content}}}<a href="{{url}}" target="_blank">查看更多&gt;&gt;</a></div>',
		"welcome_feed" : '{{#}}<div class="feed{{#first}} first{{/first}}"><div class="feed-pic"><a data-card="true" data-card-action="xpt={{xpt}}" href="{{ulink}}" target="_blank"><img data-card="true" data-card-action="xpt={{xpt}}" src="{{uavatar}}" /></a></div><div class="feed-con"><span class="username"><a data-card="true" data-card-action="xpt={{xpt}}" href="{{ulink}}" target="_blank">{{{unick}}}</a></span>{{#isauth}}<i class="authentication-min" title="我的搜狐认证"></i>{{/isauth}}<span class="user-suffix">：</span><span class="txt">{{{filtered_title}}}</span>{{#iscuted}}<a href="{{url}}" target="_blank">查看原文</a>{{/iscuted}}</div><div class="clear"></div></div>{{/}}',
		"setting" : '<div class="wrapper"><div class="type"><a class="arrow-left" href="javascript:;"><i class="disabled"></i></a><a class="arrow-right" href="javascript:;"><i class="disabled"></i></a><img src="http://s3.suc.itc.cn/app/assistant/fox.jpg" /></div><div class="clear"></div><div class="item legend"><strong>基本资料</strong><span class="hint">(2-12个中英文字符和数字)</span>				</div><div class="item"><label class="title-name"><span class="leftcell">助手昵称：</span><input class="text" name="nick" value="{{nick}}" maxlength="12" /></label></div><div class="item"><label class="title-name"><span class="leftcell">主人称谓：</span><input class="text" name="lord" value="{{lord}}" maxlength="12" /></label></div><div class="item legend"><strong>欢迎词管理</strong><span class="hint">(50个以内的中英文字符和数字)</span>				</div><div class="item"><textarea class="text welcome" name="welcome">{{{welcome}}}</textarea></div><div class="item legend" style="height: 23px; overflow: hidden;"><strong class="leftcell">透明效果</strong><div class="progress-bar"><div class="left"></div><div class="middle"><span></span><i></i></div><div class="right"></div></div><span class="hint percent">{{{percent}}}%</span><div class="clear"></div></div><div class="item"><strong class="leftcell" style="vertical-align: top;">消息提示</strong><span class="msg-option"><label><input type="checkbox" name="whisper" {{#whisper}}checked="checked"{{/whisper}} /><span>收到短消息</span></label><label><input type="checkbox" name="inform" {{#inform}}checked="checked"{{/inform}} /><span>收到通知</span></label><!--<label><input type="checkbox" name="quest" {{#quest}}checked="checked"{{/quest}} /><span>完成任务</span></label>--><label><input type="checkbox" name="festival" {{#festival}}checked="checked"{{/festival}} /><span>节日提醒</span></label><label><input type="checkbox" name="event" {{#event}}checked="checked"{{/event}} /><span>重大事件</span></label><label><input type="checkbox" name="all" {{#all}}checked="checked"{{/all}} /><span>全部</span></label></span></div></div>',
		"help" : '<div class="general"><span class="general">亲爱的<span class="lord">{{{lord}}}</span>，您想了解哪些方面的问题？</span><span class="not-general">这里都是与<span class="title"></span>相关的问题</span><ul class="general">{{#questions}}<li><a href="javascript:;" data-index="{{@}}" class="item">与{{{0}}}相关的问题。</a></li>{{/questions}}</ul><ul class="not-general"></ul><a class="back not-general" href="javascript:;">返回&gt;&gt;</a></div><p class="extra">以上信息是否可以帮助您解决问题？或者咨询<a href="http://sohucallcenter.blog.sohu.com/" target="_blank">客服中心</a>和<a href="http://me.sohu.com/online_service.jsp?pid=5" target="_blank">在线客服</a>，还能通过<a href="http://feedback.q.sohu.com/" target="_blank">意见反馈</a>向我们反馈问题。</p>'
	}));
});
